# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d7c4966a4784f0113e43c681598fc2adb6ce147f7f2538ce94090fce2725c59d8e9803ac92afa332e1c8aabd6e65830b75e0634aca46c70aa8b1885b4fd1c04

test:
  secret_key_base: 938bfa82107f16f7b1768b95afecfdbd2fd66b5a4f6027fddd64b36d5a977c52e3147903e310196490deadff2ba6de7a42b8f02628a2700a3a90201b7d25b7d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
